### ISSUE TITLE
What's a "goad" spectral score?

### ISSUE THREAD

**Issue by gvanrossum** [tim-one/tinyrand#1]
https://github.com/tim-one/tinyrand/blob/f6d822089ebf3cc9123e0fc07400fbfc8cacedd7/src/tinyrand.py#L83

**Comment by tim-one** [comment]
It's folklore :wink:. Details here:

https://en.wikipedia.org/wiki/Spectral_test

In context it's not really relevant, because "Bays-Durham shuffling" overcomes low-order bit regularities regardless of spectral score. The important thing is that the multiplier less 1 is divisible by 4, but not divisible by 8. The "divisible by 4" part is necessary to achieve the full period, but "not divisible by 8" is more a folklore "rule of thumb".

But the literature on LCGs is massive, and I don't intend to explain any of it in comments. Just relevant top-line results.

**Comment by tim-one** [comment]
Of is this about the misspelling "goad"? That should be "good", of course.

**Comment by tim-one** [comment]
Spelling error fixed now.
